#pragma once

enum class Screen {
    LOGIN,
    MENU,
    STUDENT_MENU,
    COURSE_MENU,
    FACULTY_MENU,
    ADD_STUDENT,
    DISPLAY_STUDENTS,
    UPDATE_STUDENT,
    DELETE_STUDENT,
    ADD_COURSE,
    DISPLAY_COURSES,
    UPDATE_COURSE,
    DELETE_COURSE,
    ADD_FACULTY,
    DISPLAY_FACULTY,
    UPDATE_FACULTY,
    DELETE_FACULTY,
    TAKE_ATTENDANCE,
    DISPLAY_ATTENDANCE
};